config_export_ignore.settings_form:
  title: 'Config Split Ignore Configuration'
  route_name: config_export_ignore.settings_form
  description: 'Ignore configuration while exporting using config split.'
  parent: system.admin_config_system
  weight: 99
