name: Config Export Ignore
type: module
description: Allows to ignore configurations while exporting via config split
# core: 8.x
package: Config
dependencies:
  - drupal:config_split

# Information added by Drupal.org packaging script on 2018-03-17
version: '8.x-1.0-rc1'
core: '8.x'
project: 'config_export_ignore'
datestamp: 1521283087
