
config_export_ignore.settings_form:
  path: 'admin/config/development/configuration/config-split/ignore'
  defaults:
    _form: '\Drupal\config_export_ignore\Form\SettingsForm'
    _title: 'SettingsForm'
  requirements:
    _permission: 'administer site configuration'
  options:
    _admin_route: TRUE
